version: '3'

services:
  discovery:
    container_name: discovery
    build:
      context: ./depends/discovery

  register-center:
    container_name: register-center
    build:
      context: .
    ports:
      - "8089:8000"
      - "9093:9000"
    environment:
      DISCOVERY_ADDR: "discovery:7171"
      KONG_ADMIN_ADDR: "http://127.0.0.1:8001"
    depends_on:
      - discovery

#  test:
#    container_name: test
#    build:
#      context: test/
#    ports:
#      - "9747:9747"
#      - "8747:8747"
#    environment:
#      DISCOVERY_ADDR: "discovery:7171"
#      REGISTER_CENTER: "register-center:8089"
#    depends_on:
#      - register-center